### ISSUE TITLE
MxAnalyzer doesn't work

### ISSUE THREAD

**Issue by alebaran** [fumitoh/modelx#11]
I've just tried to follow all the instructions to use MxAnalyzer. It shows the value of the variable , but no dependencies (see the screenshot).
![MxAnalyzer issue](https://user-images.githubusercontent.com/55485247/65134141-b8165200-d9fb-11e9-82e2-be41207fcc0f.jpg)

When I click on the variable or the arrow next to it, Spyder closes (dies).
Spyder version 3.3.6

**Comment by fumitoh** [comment]
I had the same issue sometimes when I switched between different versions of Spyders for testing.
When I remove all `__pycache__` folders in `spyder_modelx` package folder, the issue seems to go away. Try that and let me know if the issue still persists.

**Comment by alebaran** [comment]
I've tried it. Doesn't help.

**Comment by fumitoh** [comment]
How about putting the cursor on the row (but not clicking the arrow) and pressing -> key. Can you open the row?

**Comment by alebaran** [comment]
that works. thanks

**Comment by fumitoh** [comment]
Now you can click the arrow and it's working (even after restarting Spyer)

**Comment by alebaran** [comment]
It breaks after restarting Spyder

**Comment by fumitoh** [comment]
Strange. It's working fine now on my PC and I can't even reproduce the issue. Anyhow, this would probably take some time to get resolved.

**Comment by fumitoh** [comment]
I just released spyder-modelx v0.7.0 and this issue is fixed. Also MxAnalyzer has been significantly enhanced.
