### ISSUE TITLE
Implement uncached Cells

### ISSUE THREAD

**Issue by fumitoh** [fumitoh/modelx#125]
TBD

**Comment by AB-Athene** [comment]
Is the alternative to use custom imported modules for this purpose?

**Comment by fumitoh** [comment]
Yes, this can be used like a normal Python function.

**Comment by fumitoh** [comment]
Example

```python
import modelx as mx

@mx.defcells
def cash_inflows():
    return [1, 2, 3]

@mx.defcells
def cash_outflows():
    return [2, 1, 0]


@mx.defcells
def get_pv(cashflows: list):
    # foo()
    rate = 0.05
    disc = 1 / (1 + rate)
    return sum(v * disc**(i + 1) for i, v in enumerate(cashflows))

get_pv.is_cached = False

@mx.defcells
def pv_inflows():
    return get_pv(cash_inflows())


@mx.defcells
def pv_outflows():
    return get_pv(cash_outflows())

@mx.defcells
def pv_netflows():
    return get_pv([i - o for i, o in zip(cash_inflows(), cash_outflows())])


print(f"pv_netflows():{pv_netflows()}")
print(f"pv_inflows() - pv_outflows():{pv_inflows() - pv_outflows()}")
```

**Comment by AB-Athene** [comment]
I like the imported module approach as it creates a clear split between regular Python functions and modelx grid functionality.

**Comment by fumitoh** [comment]
You mean by the importe module approach the way you import modules by `new_module`?

**Comment by fumitoh** [comment]
This is a new feature. The import module approach is still available. I'll blog about pros and cons after introducing this.

**Comment by fumitoh** [comment]
Completed with [the release of modelx v0.27.0](https://github.com/fumitoh/modelx/releases/tag/v0.27.0)
