### ISSUE TITLE
Version 0.24 and Python 3.12

### ISSUE THREAD

**Issue by alexeybaran** [fumitoh/modelx#126]
It looks like for our purpose v0.24 works well with Python 3.12. At the same time I see that v0.25 includes specific changes for Python 3.12. Are we missing something?

Note that we are struggling to make use of v0.25. We'll raise a separate issue about it.

**Comment by fumitoh** [comment]
[This change](https://docs.modelx.io/en/latest/releases/relnotes_v0_25_0.html#spec-changes-due-to-c-level-recursion-avoidance) is for models that have deep recursion. If you're model don't have deep recursion, then it should work fine with Python 3.12 and modelx 0.24.

To use modelx 0.25, you may need  to make manual change to the model. (changing `foo[]` to `foo()`, `foo.xxx` to `_space.foo.xxx` inside formulas)

[Here](https://github.com/lifelib-dev/lifelib/commit/006e7b0bffa18285076592ce2a573acc510122a8) is an example how to apply changes.

**Comment by alexeybaran** [comment]
Thank you!
