### ISSUE TITLE
Expose maxlen parameter for tracemessage

### ISSUE THREAD

**Issue by AB-Athene** [fumitoh/modelx#144]
Default `tracemessage` `maxlen=6` is usually insufficient to see the source of circularity for complex models. I usually hardcode 20 instead. Would it be possible to increase the default or expose the parameter to allow setting it, when `modelx `is imported?
![tracemessage maxlen](https://github.com/user-attachments/assets/9869a9e1-dd69-484f-b6b6-d94fab66d462)

**Comment by fumitoh** [comment]
Increasing the default value to 20 is easier. Will reflect it in the next release.
