### ISSUE TITLE
Error log contains only function name, not arguments, with which it was called

### ISSUE THREAD

**Issue by alebaran** [fumitoh/modelx#16]
When for some reason the value of the cell can't be evaluated, the error log contains only function name, not arguments, with which it was called. E.g.:
```
Traceback (most recent call last):
  File "<string>", line 3, in CF_discounted_df
  File "...\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 204, in __setitem__
    indexer = self._get_setitem_indexer(key)
```
It would really be helpful for troubleshooting to see the arguments with which function `CF_discounted_df` was called.

**Comment by alebaran** [comment]
And on more thing :-) It would be extremely helpful to see the code in the line, which broke.

**Comment by alebaran** [comment]
+ space_args for dynamic space :-)

**Comment by fumitoh** [comment]
v0.6.0 should meet this request.
https://modelx.readthedocs.io/en/latest/releases/relnotes_v0_6_0.html

**Comment by alexeybaran** [comment]
Thank you for this development. Unfortunately it breaks in case function is used within the cell:
```
from modelx import *
m, s = new_model(), new_space()
@defcells
def a(t):
    if t > 0:
        return sum([a(t - i) for i in range(1, 2)])
    else:
        raise ValueError()

a(1)
```
