### ISSUE TITLE
Cell provided as an argument to another cell is converted to the value

### ISSUE THREAD

**Issue by alebaran** [fumitoh/modelx#19]
What is the reason that a cell provided as an argument to another cell is converted to the value? II was trying to build generic cell operating on outputs of the other cells with multiple arguments.

**Comment by fumitoh** [comment]
No-param cells can be coerced to types like Numeric:

```
@defcells
def foo():
    return 3
    
foo + 2   # => 5
```
Passing a non-param Cells to another cells parameter makes it unclear whether you're dealing with a Cells object, or its value.

**Comment by fumitoh** [comment]
Thanks for your comment. That makes sense too.

**Comment by fumitoh** [comment]
On second thought, `foo is True` and `foo == True` having different results is no less legitimate
than `[1] is [1]` and `[1] == [1]` having different results.

I will consider dropping conversion to value as an argument to another cells for a performance reason,
but coercion will probably stay.

**Comment by alebaran** [comment]
In my view, the main guiding principle of interfacing with cells is to have it as much as possible consistent with Python functions. In this way, on one hand, you benefit from the flexibility and unambiguity embedded in the Python functions design. On the other, you simplify modelx learning for people familiar with native Python constructs.
From the perspective above, I don't like inconsistency introduced by coercion as Python functions don't have that. E.g.:
```
def a():
    return 1
a
```
Inconsistency with Python functions is also the reason I've raised the original point about conversion to value.

Another situation I've observed, when modelx behaves differently from native Python is the following:
```
from modelx import *
m, s = new_model(), new_space()

@defcells
def a(*args, **kwargs):
    pass

s.a()
```
It breaks with a message
```
Traceback (most recent call last):
  File "...\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-4a687b62d56a>", line 1, in <module>
    s.a()
  File "...\Anaconda3\lib\site-packages\modelx\core\cells.py", line 77, in __call__
    return self._impl.get_value(args, kwargs)
  File "...\Anaconda3\lib\site-packages\modelx\core\cells.py", line 565, in get_value
    if self.has_cell(key):
  File "...\lib\site-packages\modelx\core\cells.py", line 466, in has_cell
    return key in self.data
TypeError: unhashable type: 'dict'
```

**Comment by alebaran** [comment]
What is the reason `**kwargs` don't work? It would be helpful to have it.

**Comment by fumitoh** [comment]
For one, modelx holds arg-value pairs in `dict`. kwargs is a dict, not hashable, so cannot be used as a dict key.

**Comment by fumitoh** [comment]
https://github.com/fumitoh/modelx/issues/19#issuecomment-549388853
Implicit conversion to value as an argument to another cells is dropped since v0.5.0.
https://modelx.readthedocs.io/en/latest/releases/relnotes_v0_5_0.html
