### ISSUE TITLE
"parent" not defined in dynamic space formula

### ISSUE THREAD

**Issue by alebaran** [fumitoh/modelx#26]
What is the reason "parent" not defined in dynamic space formula? See the code below.

```
from modelx import *
new_model()
def s_arg(t):
    print(parent)
    pass

s = new_space(formula=s_arg)
s(1)
```

**Comment by fumitoh** [comment]
Try `_space.parent`. `_space` is `s` itself.

**Comment by alebaran** [comment]
Thank you. Why didn't work at the first place? I thought dynamic space formula is evaluated in the base space namespace, which has parent.

**Comment by fumitoh** [comment]
You're right. The dynamic space formula is evaluated in the base space namespace. 
It's just that the namespace is different from `dir(s) `
