### ISSUE TITLE
String cell arguments shown without parentheses in preds

### ISSUE THREAD

**Issue by alebaran** [fumitoh/modelx#27]
String cell arguments are shown without parentheses in `preds`.
```
from modelx import *
m,s = new_model('m'), new_space('s')
@defcells
def a(name):
    return 'Hello ' + name

@defcells
def b(name):
    return a(name)

b('World')
b.preds('World')
```

It returns `[m.s.a(name=World)=Hello World]`. This makes it inconvenient, if I want to follow through the dependencies by calling `m.s.a(name=World)`. It would be much more convenient if the `preds`  function returned `[m.s.a(name='World')='Hello World]'`. Parentheses around the output aren't important.

**Comment by fumitoh** [comment]
`[m.s.a(name=World)=Hello World]` is a list with one element. 
The element is a CellNode object and its `repr` is `"m.s.a(name=World)=Hello World"` .
I can change that `repr` to the way you want, 
but  you can extract `"World"` and `"Hello World"` by

`b.preds('World')[0].args[0]`

and 

`b.preds('World')[0].value`

**Comment by alebaran** [comment]
Thank you!

**Comment by fumitoh** [comment]
modelx v0.2.0 double-quotes strings in repr. 
https://modelx.readthedocs.io/en/latest/releases/relnotes_v0_2_0.html

**Comment by alebaran** [comment]
Thank you!
