### ISSUE TITLE
spyder not opening upon install spyder-modelx

### ISSUE THREAD

**Issue by kaustavSen** [fumitoh/modelx#28]
Upon install spyder-modelx plugin using the following command:
`pip install --no-deps spyder-modelx`

spyder stops working (does not open) and gives the following error message:

![image](https://user-images.githubusercontent.com/16508583/73417248-73051380-433d-11ea-9cee-a7932266d11d.png)

**Comment by fumitoh** [comment]
What are the versions of Spyder and Python?

**Comment by kaustavSen** [comment]
Python 3.7.3
Spyder 4.0.1

**Comment by fumitoh** [comment]
Haven't tested with Spyder 4.0.1.
Use 4.0.0 for now if you can.

**Comment by kaustavSen** [comment]
Okay, thanks. Will try using Spyder 4.0.0 and see how it goes.

**Comment by kaustavSen** [comment]
Tried using spyder 4.0.0 as well.  Still getting the same error as above.  I am using spyder-modelx 0.1.0.

As soon as I uninstall spyder-modelx, spyder starts to open and works fine

**Comment by fumitoh** [comment]
Just released spyder-modelx v0.1.1 on PyPI to fix the issue. Try it out and see how it goes.
Don't forget PIP's `--no-deps` option or you mess up your conda environment.

**Comment by kaustavSen** [comment]
It's now working perfectly.  Thanks a lot for fixing this.
