### ISSUE TITLE
MyExplorer not showing formula under Spyder

### ISSUE THREAD

**Issue by kevinwong15** [fumitoh/modelx#29]
I have followed the instruction on https://modelx.readthedocs.io/en/latest/spyder.html to install the spyder plugin though I am not able to show the formula after clicking "Show Formula."

I also tried it on another PC without success. My spyder version is 3.3.6.

![image](https://user-images.githubusercontent.com/11141465/76474065-8cc26c00-644e-11ea-8341-c8f2aa66f4ed.png)

**Comment by fumitoh** [comment]
Put your cursor on Space1 in MxExplorer and do it again?

**Comment by kevinwong15** [comment]
Thank you. It's working..
