### ISSUE TITLE
Is there a way to print what's inside type Space?

### ISSUE THREAD

**Issue by Sheing** [fumitoh/modelx#3]
I wanted to get more infos from type Space, I tried JSON dumps(space), but failed.

**Comment by fumitoh** [comment]
Assuming `space` is in `model`, try:

```
from PyQt5.QtWidgets import QApplication
app = QApplication.instance()
if not app:
    app = QApplication(sys.argv)

view = get_modeltree(mx.cur_model())
view.show()
app.exec_()
```
<img width="218" alt="figure_1" src="https://user-images.githubusercontent.com/8450892/36910385-f35b7140-1e83-11e8-9533-78402005198f.png">

**Comment by Sheing** [comment]
Thanks for the quick reply, it works. I found out there's another tiny error --> from modelx.core.cells import CellPointer, CellPointer is not defined in space, you might want to comment out CellPointer.

**Comment by fumitoh** [comment]
I assume you're referring to a line in `sample_lifetable.py`. This sample is not maintained so I'll remove the file from repo. Thanks for pointing that out.
