### ISSUE TITLE
model write: pickled pandas objects aren't backward competible, when updating pandas

### ISSUE THREAD

**Issue by alebaran** [fumitoh/modelx#34]
Not a big thing, but I have noticed that when I've upgraded pandas from 0.25.3 to 1.0.4, I wasn't able to load previously saved model versions. Object structure probably changed a bit and it wasn't loading correctly. I was able to reproduce the issue by using 
`pickle.dump( pd.DataFrame(['a','b'],index=pd.MultiIndex.from_tuples(((1,2,3),(2,4,5)))), open( "try", "wb" ) )`
with the older version and 
`pickle.load(open(r'try', "rb"))`
with the newer one.

Pandas itself provides pickling function, which seems to ensure backward compatibility. The following works:
`pd.DataFrame(['a','b'],index=pd.MultiIndex.from_tuples(((1,2,3),(2,4,5)))).to_pickle('try')`
with the older version and
`pd.read_pickle('try')`
with the newer one.

It would be nice to have to use native pandas pickling.

**Comment by fumitoh** [comment]
`read_pickle` seems to have exception handling for backward compatibility
https://github.com/pandas-dev/pandas/blob/v1.0.4/pandas/io/pickle.py#L187
This can't be fixed as DataFrames are not pickled individually in modelx

**Comment by alebaran** [comment]
I guess they also rarely change the structure

**Comment by fumitoh** [comment]
This was rather a critical issue so I decided to fix it.
