### ISSUE TITLE
qtpy.QtWidgets issue

### ISSUE THREAD

**Issue by alexeybaran** [fumitoh/modelx#38]
I have been fighting for a long time with configuration of xlwings to make the following modelx line to work with it:
`from qtpy.QtWidgets import QApplication`
Sometimes I succedded, but with the recent Anaconda update I have this issue again.

I don't use QApplication GUI. The problem seems to be that the import command doesn't break immediately and somewhere underneath it throws 
`qtpy.PythonQtError:   No Qt bindings could be found         raise PythonQtError('No Qt   bindings could be found')`
This errors isn't catched by `except ImportError` statement in the code and xlwings crashes.

So I'm now commenting out line
`from modelx.qtgui.api import *`
in the modelx `__init__.py`, but that's ugly

**Comment by fumitoh** [comment]
I noticed this and 95e2e13 fixed it. This will be reflected in the next release.
