### ISSUE TITLE
Saving previously zipped model with embedded module

### ISSUE THREAD

**Issue by alexeybaran** [fumitoh/modelx#45]
There is a problem, when saving previously zipped model with embedded module. The issue seems to be that the module code isn't available for saving function as the temporary folder is removed after opening of the model.
```
import modelx as mx
m = mx.new_model()
m.new_module('gf', 'generic_func.py', 'generic_func.py')
m.zip('m.zip')
m2 = mx.read_model('m.zip')
m2.zip('m2.zip')
```

**Comment by fumitoh** [comment]
Just released v0.14.0 and this issue is fixed.
