### ISSUE TITLE
Importing modules

### ISSUE THREAD

**Issue by defrule** [fumitoh/modelx#8]
Not sure if this is an issue or intended. I wanted to use numpy so that each 'cell' represents an array.

In my example below 'unit_reserve_opening' is the opening account value at each projection timestep, but it get numpy to work, I had to import it within the function. Putting the import at the top of the module didn't work.

```
@defcells
def unit_reserve_opening(t):
    import numpy as np
    if t == 1:
        return np.array([200, 300, 100, 400])
    else:
        return unit_reserve_closing(t-1)
```

**Comment by fumitoh** [comment]
You can do:

```
import modelx as mx
import numpy

m, s = mx.new_model(), mx.new_space()

m.np = numpy

@mx.defcells
def unit_reserve_opening(t):
    # your code
```


Or instead of `m.np = numpy`,  `s.np = numpy`  can limit the use of the name `np` within the space

**Comment by kinshulsharma** [comment]
Hi Sir, 
I was facing a problem. the space inheritance is not working in Spyder in modelx. I even tried copy pasting the example you mentioned in your blog in 'More Complex Example' ( http://docs.modelx.io/en/latest/tutorial.html#more-complex-example ). I was unable to use life space as the base in term life space. 
Kindly help.
I'm currently using version 3.3.2 of spyder and 0.0.20 of modelx.

**Comment by fumitoh** [comment]
@kinshulsharma 
Please create a new issue of your own problem and delete the comment above.

**Comment by alexeybaran** [comment]
It won't be possible to save the model, if imported modules are added as refs.
In the example above if I add:
`m.save('my_model.mx')`

It breaks with message:

> TypeError: can't pickle module objects

**Comment by alexeybaran** [comment]
Btw. it is possible to save it with "write_model" feature, which is an awesome functionality. The only limitation of it is that "read_model" doesn't have a model name as a second parameter (like "open_model").

**Comment by fumitoh** [comment]
Thanks. I'll see if I can add renaming feature to `read_model`.

**Comment by alexeybaran** [comment]
I use model.save including custom class objects stored in the cells. E.g. bond class. Is there a way to do it with "write_model"?

**Comment by fumitoh** [comment]
Currently it's not possible.  `write_model` doesn't store cells values except for those cells that are created from `new_cells_from_*` or `new_space_from_*` methods, which are saved with their data source files.
In future, it may become possible to store input values with `write_model`.

**Comment by alexeybaran** [comment]
What do you call input values?

**Comment by fumitoh** [comment]
I meant by input values those values stored in cells by the user through value assignment operations as opposed to those that are calculated by the formulas of the cells. Currently no information is held to distinguish between them, so need some work.

**Comment by fumitoh** [comment]
Just released v0.0.24 and those features are made available. 
See https://modelx.readthedocs.io/en/latest/releases/relnotes_v0_0_24.html

**Comment by alexeybaran** [comment]
This really helps. Thank you very much

**Comment by fumitoh** [comment]
modelx version 0.1.0 is released, and input values of a cells are distinguished from calculated values, and they are saved by `write_model` function.
See the release note for the details.
https://modelx.readthedocs.io/en/latest/releases/relnotes_v0_1_0.html

**Comment by fumitoh** [comment]
Closing this issue as the discussion derailed from the title. Post on #15 for further discussion if any.
