### ISSUE TITLE
Method to replace existing pandas object

### ISSUE THREAD

**Issue by alexeybaran** [fumitoh/modelx#85]
Is there a way to replace existing pandas object? If I run `space.new_pandas` a couple of times it breaks saying that the object already exists.

**Comment by fumitoh** [comment]
`Model.update_pandas` should do tha job. Note that you pass the old and new pandas objects to the method.
https://docs.modelx.io/en/latest/reference/generated/modelx.core.model.Model.update_pandas.html

**Comment by alexeybaran** [comment]
Perfect, thank you!
