### ISSUE TITLE
How to run the model from IPython in Spyder?

### ISSUE THREAD

**Issue by AADYABAJAJ** [fumitoh/modelx#86]
Hi All, 

My spyder has the modelx plugin, and I am able to extract the results out of the model by using the MxConsole. But I am not able to do this if I want to do to this through a .py file, i.e., through the Ipython console.

Could you please share the code that could be written to run the model and extract the results to do this?

This is the code I wrote to run the model and extract the results:

```python
import modelx as mx 
import lifelib
lifelib.create('basiclife','Demo')

model = mx.BasicTerm_M

result_pv() 

df = pd.DataFrame(result_pv())

writer = pd.ExcelWriter('Results.xlsx',engine='xlsxwriter')

df.to_excel(writer,sheet_name='PV_Results')

writer.close() 
```

**Comment by fumitoh** [comment]
Given that a copy of `basiclife` exists in the current directory,
you can put the code below in .py file and run it to get the results.

```python
import modelx as mx 

model = mx.read_model("basiclife/BasicTerm_M")

model.Projection.result_pv().to_excel("Results.xlsx", sheet_name="PV_Results")
```

**Comment by AADYABAJAJ** [comment]
Thank you very much for your prompt response - this helps!
