### ISSUE TITLE
NameError: name 'defcells' is not defined

### ISSUE THREAD

**Issue by kinshulsharma** [fumitoh/modelx#9]
Hi Sir,
I was facing a problem. the space inheritance is not working in Spyder in modelx. I even tried copy pasting the example you mentioned in your blog in 'More Complex Example' ( http://docs.modelx.io/en/latest/tutorial.html#more-complex-example ). I was unable to use life space as the base in term life space.
Kindly help.
I'm currently using version 3.3.2 of spyder and 0.0.20 of modelx.

**Comment by fumitoh** [comment]
I ran the following code in Spyder 3.3.2 with modelx 0.0.20

```
from modelx import *

model, life = new_model(), new_space('Life')

def l(x):
    if x == x0:
        return 100000
    else:
        return l(x - 1) - d(x - 1)

def d(x):
    return l(x) * q

def q():
    return 0.003

l, d, q = defcells(l, d, q)
life.x0 = 50

term_life = model.new_space(name='TermLife', bases=life)

@defcells
def benefits(x):
    if x < x0 + n:
        return d(x) / l(x0)
    if x <= x0 + n:
        return 0

@defcells
def pv_benefits(x):
    if x < x0:
        return 0
    elif x <= x0 + n:
        return benefits(x) + pv_benefits(x + 1) / (1 + disc_rate)
    else:
        return 0
    
term_life.n = 10
term_life.disc_rate = 0
```
And I ran the following commands in a console.
```
term_life.pv_benefits(50)
Out[2]: 0.02959822305108317

term_life.frame
Out[3]: 
                   l           d      q  benefits  pv_benefits
x                                                             
 50.0  100000.000000  300.000000    NaN  0.003000     0.029598
 51.0   99700.000000  299.100000    NaN  0.002991     0.026598
 52.0   99400.900000  298.202700    NaN  0.002982     0.023607
 53.0   99102.697300  297.308092    NaN  0.002973     0.020625
 54.0   98805.389208  296.416168    NaN  0.002964     0.017652
 55.0   98508.973040  295.526919    NaN  0.002955     0.014688
 56.0   98213.446121  294.640338    NaN  0.002946     0.011733
 57.0   97918.805783  293.756417    NaN  0.002938     0.008786
 58.0   97625.049366  292.875148    NaN  0.002929     0.005849
 59.0   97332.174218  291.996523    NaN  0.002920     0.002920
NaN              NaN         NaN  0.003       NaN          NaN
 60.0            NaN         NaN    NaN  0.000000     0.000000
 61.0            NaN         NaN    NaN       NaN     0.000000
```
The result is as expected. What do you mean by "unable to use life space as the base in term life space"?

**Comment by kinshulsharma** [comment]
Hi Sir
I don't use modelx API functions in main module.

**Comment by fumitoh** [comment]
`defcells` is not imported as the error message says. Insert `from modelx import defcells` at the top.

**Comment by kinshulsharma** [comment]
Yes sir, the code is working now.

However, I was trying to replicate the build input code created by you. I have put several efforts into it but still I'm unable to get rid of the following error, kindly help.

file:///C:/Users/Dell/Desktop/ipython.html

**Comment by fumitoh** [comment]
I don't understand what you mean by "the build input code created by you".

**Comment by kinshulsharma** [comment]
I'm talking about the following code:

"""Module to create ``Input`` space and its child spaces from input data.

This module contains a function :py:func:`build_input`,
which creates "Input" space and its subspaces by reading
input data into them from an Excel file.

.. figure:: /images/input_tree.png
    :width: 50%

By default, :py:func:`build_input` reads data from *input.xlsm* in the
same folder as this module, and the structure of ``Input`` space is illustrated
by the diagram below.


.. figure:: /images/input_drawio.png
   :width: 50%

Below are descriptions of Input spaces and its subspaces.

Input
    The parent module of all other input spaces.

    Some tables in *input.xlsm* are imported as cells directly under this space.



PolicyData
    The sample policy data read from *PolicyData* tab in *input.xlsm*.
    Records and fields of *PolicyData* represents policies and policy
    attributes respectively.
    Each record of *PolicyData* is accessible as a dynamic space under
    ``PolicyData`` space indexed by *Policy* column in the input table.
    Each field of a record is accessible as a scalar cells in the dynamic
    space corresponding to the record.

    For example::

        >>> model.Input.PolicyData[3].PolicyTerm()

    gives the value of the policy term of the policy record 3.

MortalityTables
    The sample mortality tables read from *Mortality* tab.
    For Each mortality table, a dynamic space is created indexed
    by *TableID*, and `MortalityTable` cells indexed
    by ``Sex`` and ``Age`` is created in that space.

    The script below will return the mortality rate of Male, Age 41
    from the mortality table 3::

        >>> model.Input.MortalityTables[3].MortalityTable('M', 41)


ProductSpec
    The sample product spec table read from *ProductSpec* tab.
    ``ProductSpec`` dynamic subspaces holds parameters to specify products
    as cells. The dynamic subspaces are indexed by ``Product``,
    ``PolType`` and ``Gen``, and
    each of the subspace has scalar cells defined by the columns
    of *ProductSpec* tab other than the index columns.

    Empty cells in the index columns are imported as ``None``.
    ``Cells.match`` method treats ``None`` as the wildcard when
    finding the closest matching indexes for the given arguments.


Assumption
    The sample assumption table read from *Assumption* tab.

    The ``Assumption`` space has dynamic subspaces indexed by ``Product``,
    ``PolType`` and ``Gen``, each of which has scalar cells defined by the
    columns of *Assumption* tab other than the index columns.

    Empty cells in the index columns are imported as ``None``.
    ``Cells.match`` method treats ``None`` as the wildcard when
    finding the closest matching indexes for the given arguments.

AssumptionTables
    The sample assumption table read from *AssumptionTables* tab.
    The tab holds assumptions by policy duration, such as mortality factors
    and lapse assumptions.

    Each assumption in the table is imported as a cells in the
    ``AssumptionTables`` space.

Scenarios
    The sample scenario table read from *Scenarios* tab.
    TODO


"""
import sys
import os.path as path
import time
from textwrap import dedent

default_input = path.join(path.abspath(path.dirname(__file__)), 'input.xlsm')


class _PrintElapsedTime:

    def __init__(self):
        self.last_time = time.time()

    def set_start(self, msg):
        print(msg, end='', file=sys.stderr)
        self.last_time = time.time()

    def print_time(self, msg):
        this_time = time.time()
        print(msg, "({:.2f}secs)".format(this_time - self.last_time),
              file=sys.stderr)
        self.last_time = this_time


def build_input(model, input_file=default_input):
    """Create "Input" space and its sub spaces by reading data from an Excel
    file into it.

    This function creates a space named "Input" under ``model``,
    reads tables from ``input_file`` into cells and subspaces
    under the "Input" space.

    By default, this function assumes reading data from *input.xlsm*
    located in the same folder as this module.

    Args:
        model: Model object in which 'Input' space is created.
        input_file(str): Path to the Excel input file.
    """ 

    inp = model.new_space(name='Input')
    inp.allow_none = True
    print_time = True

    print("Started loading data from 'input.xlsm'.", file=sys.stderr)

    if print_time:
        timestamp = _PrintElapsedTime()
        timestamp.set_start('Loading PolicyData...')

    policydata = inp.new_space_from_excel(
        book=input_file,
        range_='B7:O307',
        sheet='PolicyData',
        name='PolicyData',
        names_row=0,
        param_cols=[0],
        space_param_order=[0],
        cells_param_order=[])

    if print_time:
        timestamp.print_time('Done.')
        timestamp.set_start('Loading MortalityTables...')

    mortbl = inp.new_space_from_excel(
        book=input_file,
        range_='E4:Q137',
        sheet='Mortality',
        name='MortalityTables',
        names_row=0,
        param_cols=[0],
        names_col=0,
        param_rows=[1, 2],
        space_param_order=[1],
        cells_param_order=[2, 0])

    if print_time:
        timestamp.print_time('Done.')
        timestamp.set_start('Loading ProductSpec...')

    prodspec = inp.new_space(name='ProductSpec')
    prodspec.new_cells_from_excel(
        book=input_file,
        range_='B7:V22',
        sheet='ProductSpec',
        names_row=0,
        param_cols=[0, 1, 2],
        param_order=[0, 1, 2])

    if print_time:
        timestamp.print_time('Done.')
        timestamp.set_start('Loading OtherParam1...')

    inp.new_cells_from_excel(
        book=input_file,
        range_='G6:H9',
        sheet='OtherParams',
        names_row=0,
        param_cols=[0],
        param_order=[0])

    if print_time:
        timestamp.print_time('Done.')
        timestamp.set_start('Loading OtherParams2...')

    inp.new_cells_from_excel(
        book=input_file,
        range_='V6:W9',
        sheet='OtherParams',
        names_row=0,
        param_cols=[0],
        param_order=[0])

    if print_time:
        timestamp.print_time('Done.')
        timestamp.set_start('Loading Assumption...')

    asmp = inp.new_space(name='Assumption')
    asmp.new_cells_from_excel(
        book=input_file,
        range_='B7:T17',
        sheet='Assumption',
        names_row=0,
        param_cols=[0, 1, 2],
        param_order=[0, 1, 2])

    if print_time:
        timestamp.print_time('Done.')
        timestamp.set_start('Loading AssumptionTables...')

    asmptbls = inp.new_space(name='AssumptionTables')
    asmptbls.new_cells_from_excel(
        book=input_file,
        range_='B7:J27',
        sheet='AssumptionTables',
        names_row=0,
        param_cols=[0],
        param_order=[0])

    if print_time:
        timestamp.print_time('Done.')
        timestamp.set_start('Loading Scenarios...')

    scenarios = inp.new_space_from_excel(
        book=input_file,
        range_='A3:C1513',
        sheet='Scenarios',
        name='Scenarios',
        names_row=0,
        param_cols=[0, 1],
        space_param_order=[0],
        cells_param_order=[1])

    if print_time:
        timestamp.print_time('Done.')

    print(dedent("""\
        Input space and its sub spaces are saved in '[project name].mx'.
        You can load input data from the saved file instead of 'input.xlsx'
        by passing 'load_saved=True' to simplelife.build function."""),
          file=sys.stderr)

    return inp
------------------------------------------------------------------------------------------------------
And, when I tried to replicate the code I'm getting this error:

In [1]: import sys
   ...: import os.path as path
   ...: import time
   ...: from textwrap import dedent

In [2]: input_data = path.join( 'TERM_PYTHON','Term.xlsm')

In [3]: class _PrintElapsedTime:
   ...: 
   ...:     def __init__(self):
   ...:         self.last_time = time.time()
   ...: 
   ...:     def set_start(self, msg):
   ...:         print(msg, end='', file=sys.stderr)
   ...:         self.last_time = time.time()
   ...: 
   ...:     def print_time(self, msg):
   ...:         this_time = time.time()
   ...:         print(msg, "({:.2f}secs)".format(this_time - self.last_time), file=sys.stderr)
   ...:         self.last_time = this_time
   ...:         

In [4]: def build_input(Term, input_file= input_data):
   ...:     inp= Term.new_space(name= 'Input')
   ...:     inp.allow_none = True
   ...:     print_time = True
   ...:     

In [5]: print("Started loading data from 'Term.xlsm'.", file=sys.stderr)
Started loading data from 'Term.xlsm'.

In [6]: if print_time:
   ...:         timestamp = _PrintElapsedTime()
   ...:         timestamp.set_start('Loading Model Points...')
   ...:         

Traceback (most recent call last):



  File "<ipython-input-6-cfda98225d3e>", line 1, in <module>

    if print_time:

NameError: name 'print_time' is not defined

In [7]: 

In [7]:
